name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install C++
      run: sudo apt-get install g++ -y
    - name: Compile C++ code
      run: g++ main.cpp -o main
    - name: Run program
      run: ./main
